apiVersion: v1
kind: Pod
metadata:
  generateName: debug-
spec:
  containers:
  - name: debug
    image: debug
    imagePullPolicy: Never
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 3600; done;" ]
